<?php

namespace AppBundle\Repository;

/**
 * AccountNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountNameRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindOne($id)
    {

    }
}
