<?php

namespace AppBundle\Repository;

/**
 * championsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class championsRepository extends \Doctrine\ORM\EntityRepository
{
}
