<?php

namespace AppBundle\Repository;

/**
 * FavouritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouritesRepository extends \Doctrine\ORM\EntityRepository
{
}
