# app/config/security.yml
security:
    providers:
            in_memory:
                memory:
                    users:
                        ryan:
                            password: $2y$12$6gjZ.onbVBgOj4ZG00puVew7ASBXWuXCu1JyC2oRlT4vIQjXRtG1W
                            roles: 'ROLE_USER'
                        admin:
                            password: $2y$12$lbaPM3/Ba1asVLifF1v51.gj0nh9cT4ouSyrLaHy7ZXB.M/AuDjuC
                            roles: 'ROLE_ADMIN'

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }