timeline_data:
    path:  /
    defaults: { _controller: TimelineBundle:Default:getDataFromLol }

my_account:
    path:  /account
    defaults: { _controller: MyaccountBundle:Default:index }

stats_homepage:
    path:  /statistiques
    defaults: { _controller: StatsBundle:Default:sellsHistory }

ajoutfavoris:
    path: /ajoutfavoris/{id_favoris}
    defaults: {_controller: AppBundle:Favourites:addfavourites}
    requirements:
      id_favourites: \d+