home:
    path:  /
    defaults: { _controller: AppBundle:Default:home }

timeline_data:
    path:  /timeline
    defaults: { _controller: TimelineBundle:Default:index }

my_account:
    path:  /account
    defaults: { _controller: MyaccountBundle:AccountName:add }

stats_homepage:
    path:  /statistiques/{idUser}
    defaults: { _controller: StatsBundle:Default:displayStat,idUser: false }

ajoutfavoris:
    path: /ajoutfavoris/{id_favoris}
    defaults: {_controller: AppBundle:Favourites:addfavourites}
    requirements:
      id_favourites: \d+

supprfavoris:
    path: /supprfavoris/{id_favoris}
    defaults: {_controller: AppBundle:Favourites:delFavourites}
    requirements:
      id_favourites: \d+

search_player:
    path: /search
    defaults: { _controller: SearchBundle:Default:searchPlayer}
    requirements:
      _method: POST

event_homepage:
    path:     /event
    defaults: { _controller: EventBundle:Default:index }

event_participate:
    path:     /event/{idEvent}
    defaults: { _controller: EventBundle:Default:addParticipant }
    requirements:
          idUser: \d+

