AppBundle\Entity\AccountName:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AccountNameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
    manyToOne:
        user_id:
            targetEntity: User
            inversedBy: accountname
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
        game_id:
            targetEntity: Games
            inversedBy: games
            joinColumn:
                name: game_id
                referencedColumnName: id
                nullable: false
lifecycleCallbacks: {  }
