AppBundle\Entity\Comment:
    type: entity
    table: null
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        thread:
            targetEntity: AppBundle\Entity\Thread

    lifecycleCallbacks: {  }
