AppBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventName:
            type: string
            length: 255
        eventDescription:
            type: string
            length: 255
        eventDate:
            type: date
        eventPlace:
            type: string
            length: 255
        eventOwner:
            type: integer
        eventNbParticipants:
            type: integer
        eventMaxParticipant:
            type: integer
        eventMembers:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
