AppBundle\Entity\Favourites:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\FavouritesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idAccount:
            type: integer
            unique: true
            column: id_account
        idFavourites:
            type: string
            length: 255
            nullable: true
            column: id_favourites
    lifecycleCallbacks: {  }
